// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prfpksdmkdrdcgxxfugl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZnBrc2Rta2RyZGNneHhmdWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTM2ODEsImV4cCI6MjA2MjM2OTY4MX0.9xHm27PZJx6K_WG9WPdgW8D5UOj2DBV2vz1O0np4igM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);